<?php
/**
 * @file
 * Code for the Reto Pais Blog feature.
 */

include_once 'retopais_feature_blog.features.inc';

/**
 * Implements hook_node_insert().
 */
function retopais_feature_blog_node_insert($node) {
  $view_names = array();
  if ($node->type === 'blog') {
    // Clear blog views cache.
    $view_names = array(
      'blog',
    );
  }
  elseif ($node->type === 'alliance') {
    // Clear blog views cache.
    $view_names = array(
      'alianzas',
    );
  }
  foreach ($view_names as $view_name) {
    cache_clear_all('ctools_export:views_view:' . $view_name, 'cache_views', TRUE);
    cache_clear_all($view_name . ':', 'cache_views_data', TRUE);
  }
}

/**
 * Implements hook_node_update().
 */
function retopais_feature_blog_node_update($node) {
  retopais_feature_blog_insert($node);
}
