<?php
/**
 * @file
 * Code for the Reto Pais Blog feature.
 */

include_once 'retopais_feature_blog.features.inc';

/**
 * Implements hook_date_formats().
 */
function retopais_feature_blog_date_formats() {
  return array(
    // Blog date format.
    array(
      'type' => 'blog_date',
      'format' => 'd \d\e F \d\e Y',
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function retopais_feature_blog_date_format_types() {
  return array(
    'blog_date' => t('Blog date: d de F de Y'),
  );
}
