<?php
/**
 * @file
 * Code for the Reto Pais Proposals feature.
 */

include_once 'retopais_feature_proposals.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function retopais_feature_proposals_form_proposal_node_form_alter(&$form, $form_state) {
  $current_step_name = $form['#multistep']['current'];
  if (isset($form['#groups'][$current_step_name])) {
    $current_step = $form['#groups'][$current_step_name];
    $current_step_fields = $current_step->children;

    // Which button do we have in this step?
    $button = FALSE;
    if (isset($form['actions']['next'])) {
      $button = &$form['actions']['next'];
    }
    elseif (isset($form['actions']['done'])) {
      $button = &$form['actions']['done'];
    }
    if ($button) {
      foreach ($current_step_fields as $field) {
        // Only validate the fields in current step.
        $button['#limit_validation_errors'][] = array($field);
      }
    }

    // Don't validate on previous button because nothing is being saved.
    if (isset($form['actions']['previous'])) {
      $form['actions']['previous']['#limit_validation_errors'] = array();
    }

    // Remove unwanted buttons.
    if (isset($form['actions']['save'])) {
      $form['actions']['save']['#access'] = FALSE;
    }
    if (isset($form['actions']['preview'])) {
      $form['actions']['preview']['#access'] = FALSE;
    }
    if (isset($form['actions']['preview_changes'])) {
      $form['actions']['preview_changes']['#access'] = FALSE;
    }
    if (isset($form['actions']['delete'])) {
      $form['actions']['delete']['#access'] = FALSE;
    }

    // Clean form.
    $form['revision_information']['#access'] = FALSE;
    $form['author']['#access'] = FALSE;
    $form['options']['#access'] = FALSE;
    $form['menu']['#access'] = FALSE;
    $form['path']['#access'] = FALSE;
  }
}
