<?php
/**
 * @file
 * Code for the Reto Pais Proposals feature.
 */

include_once 'retopais_feature_proposals.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function retopais_feature_proposals_form_proposal_node_form_alter(&$form, $form_state) {
  $current_step_name = $form['#multistep']['current'];
  if (isset($form['#groups'][$current_step_name])) {
    $current_step = $form['#groups'][$current_step_name];
    $current_step_fields = $current_step->children;

    // Which button do we have in this step?
    $button = FALSE;
    if (isset($form['actions']['next'])) {
      $button = &$form['actions']['next'];
    }
    elseif (isset($form['actions']['done'])) {
      $button = &$form['actions']['done'];
    }
    if ($button) {
      foreach ($current_step_fields as $field) {
        if ($current_step_name === 'group_info_organizacion') {
          if ($field === 'field_organization_address' ||
            $field === 'field_organization_name') {
            $form[$field][LANGUAGE_NONE][0]['value']['#required'] = TRUE;
          }
          else {
            $form[$field][LANGUAGE_NONE]['#required'] = TRUE;
          }
        }
        // Only validate the fields in current step.
        $button['#limit_validation_errors'][] = array($field);
      }
    }

    // Don't validate on previous button because nothing is being saved.
    if (isset($form['actions']['previous'])) {
      $form['actions']['previous']['#limit_validation_errors'] = array();
    }

    // Remove unwanted buttons.
    if (isset($form['actions']['save'])) {
      $form['actions']['save']['#access'] = FALSE;
    }
    if (isset($form['actions']['preview'])) {
      $form['actions']['preview']['#access'] = FALSE;
    }
    if (isset($form['actions']['preview_changes'])) {
      $form['actions']['preview_changes']['#access'] = FALSE;
    }
    if (isset($form['actions']['delete'])) {
      $form['actions']['delete']['#access'] = FALSE;
    }

    // Clean form.
    $form['revision_information']['#access'] = FALSE;
    $form['author']['#access'] = FALSE;
    $form['options']['#access'] = FALSE;
    $form['menu']['#access'] = FALSE;
    $form['path']['#access'] = FALSE;
  }
}

/**
 * Implements hook_multistep_step_alter().
 */
function retopais_feature_proposals_multistep_step_alter(&$step, $direction, $form, $form_state) {
  $node = $form_state['node'];
  $current_step = $form['#multistep']['current'];
  $node_wrapper = entity_metadata_wrapper('node', $node);
  $solution_type = $node_wrapper->field_solution_type->value();
  $organization_way = $node_wrapper->field_organization_way->value();
  $new_step = retopais_feature_proposals_get_step($current_step, $direction, $solution_type, $organization_way);
  // If we get something logic.
  if ($new_step) {
    $step = $new_step;
  }
}

/**
 * Return next or previous step according to conditions given.
 */
function retopais_feature_proposals_get_step($actual_step, $direction, $solution_type, $organization_way) {
  // Sanity check.
  if ($direction !== 'next' && $direction !== 'previous') {
    return NULL;
  }

  $steps = retopais_feature_proposals_get_steps_info();
  // For internal use.
  $organization_way = $organization_way === 'organization' ? $organization_way : 'other';

  $index = 0;
  $previous_step = NULL;
  $get_next = FALSE;
  foreach ($steps[$solution_type][$organization_way] as $group_name => $titles) {
    // If next was requested in previous iteration.
    if ($get_next) {
      return $group_name;
    }

    if ($actual_step === $group_name) {
      if ($direction === 'next') {
        $get_next = TRUE;
      }
      else {
        return $previous_step;
      }
    }

    // Still not requested? Update previous_step.
    $previous_step = $group_name;
  }

  // We never should get here, but let's keep it sane.
  return NULL;
}

/**
 * Return steps info.
 */
function retopais_feature_proposals_get_steps_info() {
  $steps = array(
    'idea' => array(
      'organization' => array(
        'group_inicio' => array(
          'short' => t('¿Qué deseás proponer?'),
          'long' => t('¿Qué deseás proponer?'),
        ),
        'group_info_idea' => array(
          'short' => t('Sobre la idea'),
          'long' => t('Contanos de tu idea'),
        ),
        'group_info_organizacion' => array(
          'short' => t('Sobre la Organización'),
          'long' => t('Contanos más sobre tu organización'),
        ),
        'group_porque_debo_ganar' => array(
          'short' => t('¿Por qué debo ganar?'),
          'long' => t('Contanos más sobre por qué deberías ganar este reto'),
        ),
        'group_datos_representante' => array(
          'short' => t('Datos del representante'),
          'long' => t('Datos del representante'),
        ),
      ),
      'other' => array(
        'group_inicio' => array(
          'short' => t('¿Qué deseás proponer?'),
          'long' => t('¿Qué deseás proponer?'),
        ),
        'group_info_idea' => array(
          'short' => t('Sobre la idea'),
          'long' => t('Contanos de tu idea'),
        ),
        'group_porque_debo_ganar' => array(
          'short' => t('¿Por qué debo ganar?'),
          'long' => t('Contanos más sobre por qué deberías ganar este reto'),
        ),
        'group_datos_representante' => array(
          'short' => t('Datos del representante'),
          'long' => t('Datos del representante'),
        ),
      ),
    ),
    'running_solution' => array(
      'organization' => array(
        'group_inicio' => array(
          'short' => t('¿Qué deseás proponer?'),
          'long' => t('¿Qué deseás proponer?'),
        ),
        'group_info_idea' => array(
          'short' => t('Solución en Marcha'),
          'long' => t('Contanos de tu solución en marcha'),
        ),
        'group_info_solucion_info' => array(
          'short' => t('Sobre el Proyecto'),
          'long' => t('Contanos más sobre el proyecto'),
        ),
        'group_info_organizacion' => array(
          'short' => t('Sobre la Organización'),
          'long' => t('Contanos más sobre tu organización'),
        ),
        'group_porque_debo_ganar' => array(
          'short' => t('¿Por qué debo ganar?'),
          'long' => t('Contanos más sobre por qué deberías ganar este reto'),
        ),
        'group_datos_representante' => array(
          'short' => t('Datos del representante'),
          'long' => t('Datos del representante'),
        ),
      ),
      'other' => array(
        'group_inicio' => array(
          'short' => t('¿Qué deseás proponer?'),
          'long' => t('¿Qué deseás proponer?'),
        ),
        'group_info_idea' => array(
          'short' => t('Solución en Marcha'),
          'long' => t('Contanos de tu solución en marcha'),
        ),
        'group_info_solucion_info' => array(
          'short' => t('Sobre el Proyecto'),
          'long' => t('Contanos más sobre el proyecto'),
        ),
        'group_porque_debo_ganar' => array(
          'short' => t('¿Por qué debo ganar?'),
          'long' => t('Contanos más sobre por qué deberías ganar este reto'),
        ),
        'group_datos_representante' => array(
          'short' => t('Datos del representante'),
          'long' => t('Datos del representante'),
        ),
      ),
    ),
  );

  return $steps;
}
