<?php
/**
 * @file
 * Reto Pais Page fullwidth layout definition.
 */

$plugin = array(
  'title'       => t('4 columns page to use with full width blocks'),
  'category'    => t('Reto País'),
  'icon'        => 'icon.png',
  'theme'       => 'retopais_fullwidth',
  'regions'     => array(
    'first-full'     => t('First full'),
    'second'         => t('Second'),
    'third-full'     => t('Third full'),
    'fourth'         => t('Fourth'),
  ),
);
