<?php

/**
 * @file
 * Main file for retopais_environment.
 */

/**
 * Implements hook_environment().
 */
function retopais_environment_environment() {
  $environments = array();

  $environments['local'] = array(
    'label' => t('Local'),
    'allowed' => array(
      'default' => TRUE,
    ),
  );
  $environments['test'] = array(
    'label' => t('Test'),
    'allowed' => array(
      'default' => FALSE,
    ),
  );
  return $environments;
}

/**
 * Implements hook_environment_switch().
 */
function retopais_environment_environment_switch($target_env, $current_env) {
  switch ($target_env) {
    case 'local':
      variable_set('environment_indicator_overwritten_name', 'Local');
      variable_set('environment_indicator_overwritten_color', '#000000');
      variable_set('environment_indicator_git_support', TRUE);
      break;

    case 'development':
      variable_set('environment_indicator_overwritten_name', 'Development');
      variable_set('environment_indicator_overwritten_color', '#006600');
      variable_set('environment_indicator_git_support', FALSE);
      break;

    case 'test':
      variable_set('environment_indicator_overwritten_name', 'Test');
      variable_set('environment_indicator_overwritten_color', '#AA3333');
      variable_set('environment_indicator_git_support', FALSE);
      break;

    case 'production':
      variable_set('environment_indicator_overwritten_name', 'Production');
      variable_set('environment_indicator_overwritten_color', '#FF0000');
      variable_set('environment_indicator_git_support', FALSE);
      break;

  }

  if ($target_env !== 'local') {
    variable_set('block_cache', '1');
    variable_set('cache', '1');
    variable_set('cache_lifetime', '0');
    variable_set('page_cache_maximum_age', '900');
    variable_set('page_compression', '1');
    variable_set('preprocess_css', '1');
    variable_set('preprocess_js', '1');
  }
}
